# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [5]:
print(A.ndim, A.shape, A.size, type(A))

2 (3, 5) 15 <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [11]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(np.exp(B))
print()
print(B.min())
print()
print(B.min(axis=1))
print()
print(B.min(axis=0))
print()
print(np.argmin(B))
print()
print(np.argmin(B, axis=1))
print()
print(B.sum())
print()
print(np.mean(B, axis=0))
print()
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [15]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

A[1] is expanded to A[1, 0:5] (A[1, :])

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [19]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [23]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [25]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Create a numpy array a with the numbers 0 to 29

Create a new array b from array a with 2 elements in first dimension, 3 in second and calculate number of elements in third dimension automaticly

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [27]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [29]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [31]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print()
b = np.array([2, 2])
print(b)
print()
print(A + b)

[[1 2]
 [3 4]]

[2 2]

[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [35]:
import numpy as np

def add_mult_matrices(A, B, add_or_multiply):
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        print('Both matrices must be of type numpy.ndarray')
        return
    match add_or_multiply:
        case 'add':
            if A.shape == B.shape:
                return A + B
            else:
                print('Matrices must have same dimensions')
                return
        case 'multiply':
            if A.shape[1] != B.shape[0]:
                print('Column of A must have same size as row of B')
                return
            else:
                return(A @ B)
        case _:
            print(f'{add_or_multiply} is not supported')
            return

A1 = np.array([[1, 2], [3, 4]])
A2 = np.array([[1, 2], [3, 4], [0, 0]])
A3 = [[1, 2], [3, 4]]
B = np.array([[1, 1], [1, 1]])

print(add_mult_matrices(A1, B, 'add'))
print()
print(add_mult_matrices(A2, B, 'multiply'))
print()
print(add_mult_matrices(B, A2, 'multiply'))
print()
print(add_mult_matrices(A1, B, 'div'))
print()
print(add_mult_matrices(A3, B, 'add'))
print()
print(add_mult_matrices(A2, B, 'add'))

[[2 3]
 [4 5]]

[[3 3]
 [7 7]
 [0 0]]

Column of A must have same size as row of B
None

div is not supported
None

Both matrices must be of type numpy.ndarray
None

Matrices must have same dimensions
None


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [37]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [39]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)  # copy
print(v2.base)  # view

None
[0 1 2 3]


In [41]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)  
print(v2)

[  0   1   2 123]
[  2 123]


In [45]:
B.ndim

2